env: local
host: http://localhost:8080
google.analytics.id: G-Z38PT7F09M

server:
  port: 8001
  forward-headers-strategy: native

anissia:
  rdb:
    driverClassName: org.h2.Driver
    jdbcUrl: "jdbc:h2:file:./tmp/anissia-local;AUTO_SERVER=TRUE"
    username: sa
    password: anissia
  ndb:
    host: localhost
    port: 9200

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      jdbc.batch_size: 4
      dialect: org.hibernate.dialect.H2Dialect
      timezone.default_storage: NORMALIZE
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    open-in-view: true
  data.elasticsearch.repositories.enabled: false
  application:
    name: anissia-core
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-critical-timeout: 30s
      config:
        import-check:
          enabled: false

